version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
      - test2
        required:
          - test

jobs:
  test:
    docker:
      - image: cimg/python:3.11.3
    steps:
      - checkout
      - run: python --version
  test2:
    docker:
      - image: cimg/aws:2023.05
    steps:
      - checkout
      - run: aws --version
