version: 2.1

jobs:
  Python:
    docker:
      - image: cimg/python:3.11.3
    steps:
      - checkout
      - run: python --version
  Aws:
    docker:
      - image: cimg/aws:2023.05
    steps:
      - checkout
      - run: aws --version

  Deploy:
    docker:
      - image: cimg/aws:2023.05
    steps:
      - run: echo "Deploying to server"
workflows:
  test-deploy:
    jobs:
      - Python
      - Aws:
          requires:
              - Python
      - Deploy
